### ISSUE TITLE
KG: A/V utstyr

### ISSUE THREAD

**Issue by askaret** [askaret/beertasting-blazor#37]
Hva har vi, hva funker (ikke)?

- [ ] Mikrofon
- [ ] Høyttalere
- [ ] Lerret
- [ ] Kanon
- [ ] TV'er
- [ ] Overganger / kabler

**Comment by RoyHalvorsen** [comment]
Jeg har Høyttalere og Mikrofon

**Comment by kiabrekke** [comment]
Lerretet funker igjen!
