### ISSUE TITLE
Innkjøp: Snacks ++

### ISSUE THREAD

**Issue by askaret** [askaret/beertasting-blazor#39]
Er dette noe som kan gjøres av Wicki?

- [ ] Wienerpølser
- [ ] Lompe, brød
- [ ] Sennep, Ketchup
- [ ] Sprøstekt løk
- [ ] Potetgull, nøtter, ++
- [ ] Brus

Må være nok til 80 personer. Det spises MYE pølse...

**Comment by kiabrekke** [comment]
Julebrus!

**Comment by kiabrekke** [comment]
Pepperkaker
